import 'package:flutter/widgets.dart';

const String oneKeepIconFontFamily = 'OneKeepIconFont';

const Map<String, IconData> _oneKeepIcons = {
  'a-068_baojianpin': IconData(0xe762, fontFamily: oneKeepIconFontFamily),
  'a-068_baoxian': IconData(0xe763, fontFamily: oneKeepIconFontFamily),
  'a-068_baoxiao': IconData(0xe764, fontFamily: oneKeepIconFontFamily),
  'a-068_bianji': IconData(0xe765, fontFamily: oneKeepIconFontFamily),
  'a-068_gongzi': IconData(0xe766, fontFamily: oneKeepIconFontFamily),
  'a-068_chongzhi': IconData(0xe767, fontFamily: oneKeepIconFontFamily),
  'a-068_fangdai': IconData(0xe768, fontFamily: oneKeepIconFontFamily),
  'a-068_dianying': IconData(0xe769, fontFamily: oneKeepIconFontFamily),
  'a-068_huazhuang': IconData(0xe76a, fontFamily: oneKeepIconFontFamily),
  'a-068_chuzuche': IconData(0xe76b, fontFamily: oneKeepIconFontFamily),
  'a-068_chalv': IconData(0xe76c, fontFamily: oneKeepIconFontFamily),
  'a-068_gongyi': IconData(0xe76d, fontFamily: oneKeepIconFontFamily),
  'a-068_gaodian': IconData(0xe76e, fontFamily: oneKeepIconFontFamily),
  'a-068_gongjiao': IconData(0xe76f, fontFamily: oneKeepIconFontFamily),
  'a-068_gouwu': IconData(0xe770, fontFamily: oneKeepIconFontFamily),
  'a-068_jizhang': IconData(0xe771, fontFamily: oneKeepIconFontFamily),
  'a-068_jiaocai': IconData(0xe772, fontFamily: oneKeepIconFontFamily),
  'a-068_chongwu': IconData(0xe773, fontFamily: oneKeepIconFontFamily),
  'a-068_huxiqi': IconData(0xe774, fontFamily: oneKeepIconFontFamily),
  'a-068_huafei': IconData(0xe775, fontFamily: oneKeepIconFontFamily),
  'a-068_jipiao': IconData(0xe776, fontFamily: oneKeepIconFontFamily),
  'a-068_jiuyi': IconData(0xe777, fontFamily: oneKeepIconFontFamily),
  'a-068_jianzhi': IconData(0xe778, fontFamily: oneKeepIconFontFamily),
  'a-068_lvyou': IconData(0xe779, fontFamily: oneKeepIconFontFamily),
  'a-068_jiayou': IconData(0xe77a, fontFamily: oneKeepIconFontFamily),
  'a-068_liwu': IconData(0xe77b, fontFamily: oneKeepIconFontFamily),
  'a-068_muying': IconData(0xe77c, fontFamily: oneKeepIconFontFamily),
  'a-068_jiaju': IconData(0xe77d, fontFamily: oneKeepIconFontFamily),
  'a-068_lijin': IconData(0xe77e, fontFamily: oneKeepIconFontFamily),
  'a-068_huoche': IconData(0xe77f, fontFamily: oneKeepIconFontFamily),
  'a-068_licai': IconData(0xe780, fontFamily: oneKeepIconFontFamily),
  'a-068_jiu': IconData(0xe781, fontFamily: oneKeepIconFontFamily),
  'a-068_jiadian': IconData(0xe782, fontFamily: oneKeepIconFontFamily),
  'a-068_shenghuo': IconData(0xe783, fontFamily: oneKeepIconFontFamily),
  'a-068_peixunfei': IconData(0xe784, fontFamily: oneKeepIconFontFamily),
  'a-068_shezhi': IconData(0xe785, fontFamily: oneKeepIconFontFamily),
  'a-068_maicai': IconData(0xe786, fontFamily: oneKeepIconFontFamily),
  'a-068_meifa': IconData(0xe787, fontFamily: oneKeepIconFontFamily),
  'a-068_shuidian': IconData(0xe788, fontFamily: oneKeepIconFontFamily),
  'a-068_lingshi': IconData(0xe789, fontFamily: oneKeepIconFontFamily),
  'a-068_shuma': IconData(0xe78a, fontFamily: oneKeepIconFontFamily),
  'a-068_qita-60': IconData(0xe78b, fontFamily: oneKeepIconFontFamily),
  'a-068_mingxi': IconData(0xe78c, fontFamily: oneKeepIconFontFamily),
  'a-068_xinyongka': IconData(0xe78d, fontFamily: oneKeepIconFontFamily),
  'a-068_yanchanghui': IconData(0xe78e, fontFamily: oneKeepIconFontFamily),
  'a-068_xuefei': IconData(0xe78f, fontFamily: oneKeepIconFontFamily),
  'a-068_tuinabaojian': IconData(0xe790, fontFamily: oneKeepIconFontFamily),
  'a-068_yongcan': IconData(0xe791, fontFamily: oneKeepIconFontFamily),
  'a-068_yinpin': IconData(0xe792, fontFamily: oneKeepIconFontFamily),
  'a-068_zaocan': IconData(0xe793, fontFamily: oneKeepIconFontFamily),
  'a-068_yifu': IconData(0xe794, fontFamily: oneKeepIconFontFamily),
  'a-068_tongji': IconData(0xe795, fontFamily: oneKeepIconFontFamily),
  'a-068_zhuanzhang': IconData(0xe796, fontFamily: oneKeepIconFontFamily),
  'a-068_shuiguo': IconData(0xe797, fontFamily: oneKeepIconFontFamily),
  'a-068_xianhua': IconData(0xe798, fontFamily: oneKeepIconFontFamily),
  'a-068_wenju': IconData(0xe799, fontFamily: oneKeepIconFontFamily),
  'a-068_zhuangxiu': IconData(0xe79a, fontFamily: oneKeepIconFontFamily),
  'a-068_tijian': IconData(0xe79b, fontFamily: oneKeepIconFontFamily),
  'a-068_tingchefei': IconData(0xe79c, fontFamily: oneKeepIconFontFamily),
  'a-068_youxi': IconData(0xe79d, fontFamily: oneKeepIconFontFamily),
  'a-068_yundong': IconData(0xe79e, fontFamily: oneKeepIconFontFamily),
  'a-068_xiaoye': IconData(0xe79f, fontFamily: oneKeepIconFontFamily),
  'a-068_yao': IconData(0xe7a0, fontFamily: oneKeepIconFontFamily),
};

const Map<String, String> _oneKeepIconLabels = {
  'a-068_baojianpin': '保健品',
  'a-068_baoxian': '保险',
  'a-068_baoxiao': '报销',
  'a-068_bianji': '编辑',
  'a-068_gongzi': '工资',
  'a-068_chongzhi': '充值',
  'a-068_fangdai': '房贷',
  'a-068_dianying': '电影',
  'a-068_huazhuang': '化妆',
  'a-068_chuzuche': '出租车',
  'a-068_chalv': '差旅',
  'a-068_gongyi': '公益',
  'a-068_gaodian': '糕点',
  'a-068_gongjiao': '公交',
  'a-068_gouwu': '购物',
  'a-068_jizhang': '记账',
  'a-068_jiaocai': '教材',
  'a-068_chongwu': '宠物',
  'a-068_huxiqi': '呼吸器',
  'a-068_huafei': '话费',
  'a-068_jipiao': '机票',
  'a-068_jiuyi': '就医',
  'a-068_jianzhi': '兼职',
  'a-068_lvyou': '旅游',
  'a-068_jiayou': '加油',
  'a-068_liwu': '礼物',
  'a-068_muying': '母婴',
  'a-068_jiaju': '家居',
  'a-068_lijin': '礼金',
  'a-068_huoche': '火车',
  'a-068_licai': '理财',
  'a-068_jiu': '酒水',
  'a-068_jiadian': '家电',
  'a-068_shenghuo': '生活',
  'a-068_peixunfei': '培训费',
  'a-068_shezhi': '设置',
  'a-068_maicai': '买菜',
  'a-068_meifa': '美发',
  'a-068_shuidian': '水电',
  'a-068_lingshi': '零食',
  'a-068_shuma': '数码',
  'a-068_qita-60': '其他',
  'a-068_mingxi': '明细',
  'a-068_xinyongka': '信用卡',
  'a-068_yanchanghui': '演唱会',
  'a-068_xuefei': '学费',
  'a-068_tuinabaojian': '推拿保健',
  'a-068_yongcan': '用餐',
  'a-068_yinpin': '饮品',
  'a-068_zaocan': '早餐',
  'a-068_yifu': '衣服',
  'a-068_tongji': '统计',
  'a-068_zhuanzhang': '转账',
  'a-068_shuiguo': '水果',
  'a-068_xianhua': '鲜花',
  'a-068_wenju': '文具',
  'a-068_zhuangxiu': '装修',
  'a-068_tijian': '体检',
  'a-068_tingchefei': '停车费',
  'a-068_youxi': '游戏',
  'a-068_yundong': '运动',
  'a-068_xiaoye': '宵夜',
  'a-068_yao': '药品',
};

IconData? oneKeepIconFont(String key) {
  return _oneKeepIcons[key];
}

String oneKeepIconLabel(String key) {
  return _oneKeepIconLabels[key] ?? key.replaceFirst('a-068_', '');
}

List<String> get oneKeepCategoryIconKeys =>
    List<String>.unmodifiable(_oneKeepIcons.keys);
